### ISSUE TITLE
'toLowerCase' of undefined

### ISSUE THREAD

**Issue by dmccarthy-tssg** [OPENi-ict/permissions_api#4]
[TypeError: Cannot call method 'toLowerCase' of undefined]
TypeError: Cannot call method 'toLowerCase' of undefined
    at parsePermissions (/home/ubuntu/repos/cloudlet-platform/node_modules/permissions_api/lib/helper.js:24:41)
    at postPermissions (/home/ubuntu/repos/cloudlet-platform/node_modules/permissions_api/lib/helper.js:118:23)
    at Object.processMongrel2Message (/home/ubuntu/repos/cloudlet-platform/node_modules/permissions_api/lib/helper.js:242:14)
    at processMessage (/home/ubuntu/repos/cloudlet-platform/node_modules/permissions_api/lib/main.js:10:24)
    at /home/ubuntu/repos/cloudlet-platform/node_modules/permissions_api/lib/main.js:49:13
    at /home/ubuntu/repos/cloudlet-platform/node_modules/permissions_api/node_modules/jsonwebtoken/index.js:65:18
    at process._tickCallback (node.js:442:13)

**Comment by dmccarthy-tssg** [comment]
added sanity check to prevent this exception from occurring
