### ISSUE TITLE
null request json body causing the system to crash

### ISSUE THREAD

**Issue by dmccarthy-tssg** [OPENi-ict/permissions_api#6]
}
[TypeError: Cannot read property 'length' of null]
TypeError: Cannot read property 'length' of null
    at parsePermissions (/home/ubuntu/repos/cloudlet-platform/node_modules/permissions_api/lib/helper.js:22:37)
    at postPermissions (/home/ubuntu/repos/cloudlet-platform/node_modules/permissions_api/lib/helper.js:123:23)
    at Object.processMongrel2Message (/home/ubuntu/repos/cloudlet-platform/node_modules/permissions_api/lib/helper.js:246:14)
    at processMessage (/home/ubuntu/repos/cloudlet-platform/node_modules/permissions_api/lib/main.js:11:24)
    at /home/ubuntu/repos/cloudlet-platform/node_modules/permissions_api/lib/main.js:52:13
    at /home/ubuntu/repos/cloudlet-platform/node_modules/permissions_api/node_modules/jsonwebtoken/index.js:65:18

**Comment by dmccarthy-tssg** [comment]
Added code to check that that the permissions body is not empty. Sends an error message back to the user.
